# Generated by Django 4.2.5 on 2023-09-24 21:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_remove_placename_point_lat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placename",
            name="slug",
        ),
        migrations.AlterField(
            model_name="placename",
            name="long_description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
    ]
