# Generated by Django 4.2.5 on 2023-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_remove_placename_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ["sequence_number"],
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
            },
        ),
        migrations.RenameField(
            model_name="placeimage",
            old_name="numb",
            new_name="sequence_number",
        ),
        migrations.AlterField(
            model_name="placename",
            name="latitude",
            field=models.FloatField(verbose_name="Широта точки"),
        ),
        migrations.AlterField(
            model_name="placename",
            name="longitude",
            field=models.FloatField(verbose_name="Долгота точки"),
        ),
    ]
