# Generated by Django 4.2.5 on 2023-10-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_placeimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placename",
            name="title",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Заголовок"
            ),
        ),
    ]
